spring:
  application:
    name: "spring-boot-4"

  # Enable API versioning
#  mvc:
#    apiversion:
#      use:
#        query-parameter: version
#        header: version

  # Open Telemetry Configuration
  tracing:
    sampling:
      probability: 1.0  # 100% sampling for production
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs

logging:
  level:
    root: INFO
    org.springframework.boot.actuator.autoconfigure.opentelemetry: DEBUG
    org.springframework.boot.docker.compose: DEBUG